# Generated by Django 3.2.7 on 2021-10-06 13:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('email', models.CharField(max_length=42)),
                ('password', models.CharField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='RecordingFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('ecgfile', models.FileField(upload_to='ECG/patient')),
                ('url', models.CharField(max_length=200)),
                ('doctor', models.CharField(max_length=20)),
                ('patient', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=42)),
                ('last_name', models.CharField(max_length=42)),
                ('age', models.IntegerField()),
                ('TZ', models.CharField(max_length=20)),
                ('birthDate', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECGAnalysis.doctor')),
            ],
            options={
                'ordering': ['age'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('record_date', models.DateField(default=django.utils.timezone.now)),
                ('file_date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECGAnalysis.patient')),
            ],
            options={
                'ordering': ['record_date'],
            },
        ),
    ]
